import { z } from 'zod'
import { getCritiques, paletteEvaluation, selectedDirection } from '../core/analysis'
import { localReferenceProvider } from '../data/referenceLibrary'
import type { AgentSuggestion, DesignDecision, Direction, Reference } from '../core/types'
import { useProjectStore } from '../store/projectStore'
import { webMcpLifecycle } from './lifecycle'

type JsonSchema = Record<string, unknown>
type WebMcpDocument = Document & { modelContext?: { registerTool?: (definition: { name: string; description: string; inputSchema: JsonSchema; annotations?: Record<string, unknown>; execute: (input: unknown) => Promise<unknown> }) => Promise<unknown>; getTools?: () => unknown | Promise<unknown>; unregisterTool?: (name: string) => Promise<void> } }
type Tool<T> = { name: string; description: string; zod: z.ZodType<T>; schema: JsonSchema; readOnly?: boolean; execute: (value: T) => unknown }

const empty = z.object({}).strict()
const emptySchema = { type: 'object', properties: {}, additionalProperties: false }
const string = { type: 'string', minLength: 1 }
const idSchema = { type: 'object', properties: { id: string }, required: ['id'], additionalProperties: false }
const id = z.object({ id: z.string().min(1) }).strict()
const result = (key: string, value: unknown) => ({ success: true, [key]: value, projectVersion: useProjectStore.getState().project.projectVersion })
const selectedReferences = () => { const project = useProjectStore.getState().project; const direction = selectedDirection(project); return project.references.filter((reference) => direction?.referenceIds.includes(reference.id)) }
const stringArray = z.array(z.string().min(1)).max(20).default([])
const colors = z.array(z.string().regex(/^#[0-9a-fA-F]{6}$/)).min(1).max(10)

const tools: Tool<any>[] = [
  { name: 'get_project_context', description: 'Read the active MOOD project, its phase, version, selected direction, and recent activity.', zod: empty, schema: emptySchema, readOnly: true, execute: () => result('project', useProjectStore.getState().project) },
  { name: 'get_references', description: 'Read all moodboard references including recoverable rejected items and their notes.', zod: empty, schema: emptySchema, readOnly: true, execute: () => result('references', useProjectStore.getState().project.references) },
  { name: 'get_selected_references', description: 'Read references attached to the currently selected direction.', zod: empty, schema: emptySchema, readOnly: true, execute: () => result('references', selectedReferences()) },
  { name: 'get_directions', description: 'Read every candidate direction and its human or agent provenance.', zod: empty, schema: emptySchema, readOnly: true, execute: () => result('directions', useProjectStore.getState().project.directions) },
  { name: 'get_selected_direction', description: 'Read the direction currently driving Refine and System.', zod: empty, schema: emptySchema, readOnly: true, execute: () => result('direction', selectedDirection(useProjectStore.getState().project)) },
  { name: 'get_design_decisions', description: 'Read traceable decisions with evidence, status, and lock state.', zod: empty, schema: emptySchema, readOnly: true, execute: () => result('decisions', useProjectStore.getState().project.designDecisions) },
  { name: 'get_design_system', description: 'Read the live design system derived from the selected direction and approved decisions.', zod: empty, schema: emptySchema, readOnly: true, execute: () => result('designSystem', useProjectStore.getState().project.designSystem) },
  { name: 'get_critiques', description: 'Read deterministic palette, contrast, hierarchy, and evidence critiques.', zod: empty, schema: emptySchema, readOnly: true, execute: () => result('critiques', getCritiques(useProjectStore.getState().project)) },
  { name: 'search_reference_library', description: 'Search the local structured reference library. No paid external API is used.', zod: z.object({ query: z.string().default(''), tags: stringArray.optional(), limit: z.number().int().min(1).max(40).default(12) }).strict(), schema: { type: 'object', properties: { query: { type: 'string' }, tags: { type: 'array', items: string, maxItems: 20 }, limit: { type: 'integer', minimum: 1, maximum: 40 } }, additionalProperties: false }, readOnly: true, execute: (input) => result('references', localReferenceProvider.search(input.query, input.tags, input.limit)) },
  { name: 'add_reference', description: 'Add one reference to the shared moodboard. Supply an image URL or data URL and useful metadata.', zod: z.object({ title: z.string().min(1), image: z.string().min(1), source: z.string().default('Agent supplied'), tags: stringArray, group: z.string().default('Agent references'), extractedColors: colors.optional(), notes: z.string().default('') }).strict(), schema: { type: 'object', properties: { title: string, image: string, source: { type: 'string' }, tags: { type: 'array', items: string }, group: { type: 'string' }, extractedColors: { type: 'array', items: { type: 'string', pattern: '^#[0-9a-fA-F]{6}$' } }, notes: { type: 'string' } }, required: ['title', 'image'], additionalProperties: false }, execute: (input) => { const reference: Reference = { id: `agent-${Date.now()}`, title: input.title, image: input.image, source: input.source, tags: input.tags, notes: input.notes, status: 'neutral', group: input.group, extractedColors: input.extractedColors ?? [], createdBy: 'agent' }; useProjectStore.getState().addReference(reference, 'agent'); return result('reference', reference) } },
  { name: 'keep_reference', description: 'Mark an existing reference as kept in the shared board.', zod: id, schema: idSchema, execute: (input) => { useProjectStore.getState().keepReference(input.id); return result('reference', useProjectStore.getState().project.references.find((reference) => reference.id === input.id)) } },
  { name: 'reject_reference', description: 'Reject an existing reference without deleting it; it can be restored later.', zod: id, schema: idSchema, execute: (input) => { useProjectStore.getState().rejectReference(input.id); return result('reference', useProjectStore.getState().project.references.find((reference) => reference.id === input.id)) } },
  { name: 'restore_reference', description: 'Restore a rejected reference to the active board.', zod: id, schema: idSchema, execute: (input) => { useProjectStore.getState().restoreReference(input.id); return result('reference', useProjectStore.getState().project.references.find((reference) => reference.id === input.id)) } },
  { name: 'add_reference_note', description: 'Attach a concise note to a reference.', zod: z.object({ id: z.string().min(1), notes: z.string().max(2000) }).strict(), schema: { type: 'object', properties: { id: string, notes: { type: 'string', maxLength: 2000 } }, required: ['id', 'notes'], additionalProperties: false }, execute: (input) => { useProjectStore.getState().addReferenceNote(input.id, input.notes); return result('reference', useProjectStore.getState().project.references.find((reference) => reference.id === input.id)) } },
  { name: 'create_direction', description: 'Create a candidate design direction. It remains editable until a human approves it.', zod: z.object({ title: z.string().min(1), statement: z.string().min(1), descriptors: stringArray, referenceIds: stringArray, palette: colors, createdBy: z.enum(['human', 'agent']).default('agent') }).strict(), schema: { type: 'object', properties: { title: string, statement: string, descriptors: { type: 'array', items: string }, referenceIds: { type: 'array', items: string }, palette: { type: 'array', items: { type: 'string', pattern: '^#[0-9a-fA-F]{6}$' }, minItems: 1 }, createdBy: { enum: ['human', 'agent'] } }, required: ['title', 'statement', 'palette'], additionalProperties: false }, execute: (input) => { const base = selectedDirection(useProjectStore.getState().project); const direction: Direction = { id: `direction-${Date.now()}`, title: input.title, statement: input.statement, descriptors: input.descriptors, referenceIds: input.referenceIds, palette: input.palette, typography: base?.typography.map((token) => ({ ...token })) ?? [], createdBy: input.createdBy, approved: false }; useProjectStore.getState().createDirection(direction); return result('direction', direction) } },
  { name: 'update_direction', description: 'Update an unlocked candidate direction title, statement, descriptors, references, or palette.', zod: z.object({ id: z.string().min(1), title: z.string().min(1).optional(), statement: z.string().min(1).optional(), descriptors: stringArray.optional(), referenceIds: stringArray.optional(), palette: colors.optional(), approved: z.boolean().optional() }).strict(), schema: { type: 'object', properties: { id: string, title: string, statement: string, descriptors: { type: 'array', items: string }, referenceIds: { type: 'array', items: string }, palette: { type: 'array', items: { type: 'string', pattern: '^#[0-9a-fA-F]{6}$' } }, approved: { type: 'boolean' } }, required: ['id'], additionalProperties: false }, execute: (input) => { const { id: directionId, ...patch } = input; useProjectStore.getState().updateDirection(directionId, patch); return result('direction', useProjectStore.getState().project.directions.find((direction) => direction.id === directionId)) } },
  { name: 'select_direction', description: 'Select a direction so Refine and System derive from it immediately.', zod: id, schema: idSchema, execute: (input) => { useProjectStore.getState().selectDirection(input.id); return result('direction', selectedDirection(useProjectStore.getState().project)) } },
  { name: 'create_design_decision', description: 'Create a traceable decision with supporting reference evidence.', zod: z.object({ category: z.string().min(1), statement: z.string().min(1), supportingReferenceIds: stringArray, createdBy: z.enum(['human', 'agent']).default('agent') }).strict(), schema: { type: 'object', properties: { category: string, statement: string, supportingReferenceIds: { type: 'array', items: string }, createdBy: { enum: ['human', 'agent'] } }, required: ['category', 'statement'], additionalProperties: false }, execute: (input) => { const decision: DesignDecision = { id: `decision-${Date.now()}`, category: input.category, statement: input.statement, supportingReferenceIds: input.supportingReferenceIds, status: 'emerging', locked: false, createdBy: input.createdBy }; useProjectStore.getState().createDecision(decision); return result('decision', decision) } },
  { name: 'update_design_decision', description: 'Update an unlocked design decision. Locked human decisions reject overwrite attempts.', zod: z.object({ id: z.string().min(1), category: z.string().min(1).optional(), statement: z.string().min(1).optional(), supportingReferenceIds: stringArray.optional(), status: z.enum(['emerging', 'approved', 'rejected']).optional() }).strict(), schema: { type: 'object', properties: { id: string, category: string, statement: string, supportingReferenceIds: { type: 'array', items: string }, status: { enum: ['emerging', 'approved', 'rejected'] } }, required: ['id'], additionalProperties: false }, execute: (input) => { const { id: decisionId, ...patch } = input; const mutation = useProjectStore.getState().updateDecision(decisionId, patch); return mutation.success ? result('decision', useProjectStore.getState().project.designDecisions.find((decision) => decision.id === decisionId)) : { success: false, error: mutation.reason, projectVersion: useProjectStore.getState().project.projectVersion } } },
  { name: 'lock_design_decision', description: 'Lock a human-approved design decision so agent updates cannot overwrite it.', zod: id, schema: idSchema, execute: (input) => { useProjectStore.getState().lockDecision(input.id); return result('decision', useProjectStore.getState().project.designDecisions.find((decision) => decision.id === input.id)) } },
  { name: 'reject_design_decision', description: 'Reject an unlocked decision while retaining its evidence trail.', zod: id, schema: idSchema, execute: (input) => { useProjectStore.getState().rejectDecision(input.id); return result('decision', useProjectStore.getState().project.designDecisions.find((decision) => decision.id === input.id)) } },
  { name: 'evaluate_palette', description: 'Run deterministic contrast and palette-distance evaluation for the selected direction.', zod: empty, schema: emptySchema, readOnly: true, execute: () => result('evaluation', paletteEvaluation(useProjectStore.getState().project)) },
  { name: 'evaluate_direction', description: 'Run deterministic direction critique covering hierarchy, contrast, palette and evidence.', zod: empty, schema: emptySchema, readOnly: true, execute: () => result('critiques', getCritiques(useProjectStore.getState().project)) },
  { name: 'create_suggestion', description: 'Create a proposed reference, palette, decision, typography, or principle mutation. It is not applied until apply_suggestion is called.', zod: z.object({ title: z.string().min(1), detail: z.string().min(1), kind: z.enum(['reference', 'palette', 'type', 'decision', 'principle']), mutation: z.discriminatedUnion('type', [z.object({ type: z.literal('update_palette'), palette: colors }), z.object({ type: z.literal('add_principle'), principle: z.string().min(1) }), z.object({ type: z.literal('update_typography'), tokenId: z.string().min(1), patch: z.object({ family: z.string().optional(), weight: z.number().int().optional(), size: z.string().optional(), lineHeight: z.string().optional() }).strict() }), z.object({ type: z.literal('create_decision'), decision: z.object({ id: z.string().min(1), category: z.string().min(1), statement: z.string().min(1), supportingReferenceIds: stringArray, status: z.enum(['emerging', 'approved', 'rejected']).default('emerging'), locked: z.boolean().default(false), createdBy: z.enum(['human', 'agent']).default('agent') }).strict() }), z.object({ type: z.literal('add_references'), references: z.array(z.object({ id: z.string().min(1), title: z.string().min(1), image: z.string().min(1), source: z.string().min(1), tags: stringArray, notes: z.string().default(''), status: z.enum(['neutral', 'kept', 'rejected']).default('neutral'), group: z.string().min(1), extractedColors: colors.default([]), createdBy: z.enum(['human', 'agent']).default('agent') }).strict()).min(1).max(12) })]) }).strict(), schema: { type: 'object', properties: { title: string, detail: string, kind: { enum: ['reference', 'palette', 'type', 'decision', 'principle'] }, mutation: { oneOf: [{ type: 'object', required: ['type', 'palette'], properties: { type: { const: 'update_palette' }, palette: { type: 'array', items: { type: 'string', pattern: '^#[0-9a-fA-F]{6}$' } } } }, { type: 'object', required: ['type', 'principle'], properties: { type: { const: 'add_principle' }, principle: string } }, { type: 'object', required: ['type', 'tokenId', 'patch'], properties: { type: { const: 'update_typography' }, tokenId: string, patch: { type: 'object' } } }, { type: 'object', required: ['type', 'decision'], properties: { type: { const: 'create_decision' }, decision: { type: 'object' } } }, { type: 'object', required: ['type', 'references'], properties: { type: { const: 'add_references' }, references: { type: 'array', minItems: 1, items: { type: 'object' } } } }] } }, required: ['title', 'detail', 'kind', 'mutation'], additionalProperties: false }, execute: (input) => { const suggestion: AgentSuggestion = { id: `suggestion-${Date.now()}`, title: input.title, detail: input.detail, kind: input.kind, origin: 'agent', status: 'proposed', mutation: input.mutation }; useProjectStore.getState().addSuggestion(suggestion); return result('suggestion', suggestion) } },
  { name: 'apply_suggestion', description: 'Apply a proposed suggestion to the shared project and return the updated version.', zod: id, schema: idSchema, execute: (input) => { const mutation = useProjectStore.getState().applySuggestion(input.id); return mutation.success ? result('suggestion', useProjectStore.getState().project.suggestions.find((suggestion) => suggestion.id === input.id)) : { success: false, error: mutation.reason, projectVersion: useProjectStore.getState().project.projectVersion } } },
  { name: 'reject_suggestion', description: 'Reject a proposed suggestion without mutating the project.', zod: id, schema: idSchema, execute: (input) => { useProjectStore.getState().rejectSuggestion(input.id); return result('suggestion', useProjectStore.getState().project.suggestions.find((suggestion) => suggestion.id === input.id)) } },
  { name: 'set_design_system', description: 'Replace the mutable design system state while preserving the selected workflow context.', zod: z.object({ mood: stringArray.optional(), shapeLanguage: z.string().optional(), photography: z.string().optional(), graphicLanguage: z.string().optional(), principles: stringArray.optional() }).strict(), schema: { type: 'object', properties: { mood: { type: 'array', items: string }, shapeLanguage: { type: 'string' }, photography: { type: 'string' }, graphicLanguage: { type: 'string' }, principles: { type: 'array', items: string } }, additionalProperties: false }, execute: (input) => { const current = useProjectStore.getState().project.designSystem; useProjectStore.getState().setDesignSystem({ ...current, ...input }); return result('designSystem', useProjectStore.getState().project.designSystem) } },
  { name: 'update_color_token', description: 'Update one design-system color token.', zod: z.object({ id: z.string().min(1), name: z.string().optional(), value: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(), role: z.string().optional(), description: z.string().optional() }).strict(), schema: { type: 'object', properties: { id: string, name: { type: 'string' }, value: { type: 'string', pattern: '^#[0-9a-fA-F]{6}$' }, role: { type: 'string' }, description: { type: 'string' } }, required: ['id'], additionalProperties: false }, execute: (input) => { const { id: tokenId, ...patch } = input; useProjectStore.getState().updateColorToken(tokenId, patch); return result('token', useProjectStore.getState().project.designSystem.colors.find((token) => token.id === tokenId)) } },
  { name: 'update_typography_token', description: 'Update one design-system typography token.', zod: z.object({ id: z.string().min(1), role: z.string().optional(), family: z.string().optional(), weight: z.number().int().min(100).max(1000).optional(), size: z.string().optional(), lineHeight: z.string().optional() }).strict(), schema: { type: 'object', properties: { id: string, role: { type: 'string' }, family: { type: 'string' }, weight: { type: 'integer', minimum: 100, maximum: 1000 }, size: { type: 'string' }, lineHeight: { type: 'string' } }, required: ['id'], additionalProperties: false }, execute: (input) => { const { id: tokenId, ...patch } = input; useProjectStore.getState().updateTypographyToken(tokenId, patch); return result('token', useProjectStore.getState().project.designSystem.typography.find((token) => token.id === tokenId)) } },
  { name: 'update_design_principle', description: 'Update an existing design-system principle by index.', zod: z.object({ index: z.number().int().min(0), principle: z.string().min(1) }).strict(), schema: { type: 'object', properties: { index: { type: 'integer', minimum: 0 }, principle: string }, required: ['index', 'principle'], additionalProperties: false }, execute: (input) => { useProjectStore.getState().updateDesignPrinciple(input.index, input.principle); return result('principles', useProjectStore.getState().project.designSystem.principles) } }
  ,{ name: 'list_projects', description: 'List all local MOOD projects available in this browser.', zod: empty, schema: emptySchema, readOnly: true, execute: () => result('projects', useProjectStore.getState().projects.map(({ id, title, brief, isDemo, projectVersion }) => ({ id, title, brief, isDemo: Boolean(isDemo), projectVersion }))) }
  ,{ name: 'create_project', description: 'Create and open a new local MOOD project with a creative brief.', zod: z.object({ name: z.string().min(1), brief: z.string().min(1), avoid: stringArray.optional() }).strict(), schema: { type: 'object', properties: { name: string, brief: string, avoid: { type: 'array', items: string } }, required: ['name', 'brief'], additionalProperties: false }, execute: (input) => { const project = useProjectStore.getState().createProject(input); return result('project', project) } }
  ,{ name: 'open_project', description: 'Open one existing MOOD project so subsequent tools operate on it.', zod: id, schema: idSchema, execute: (input) => { const success = useProjectStore.getState().openProject(input.id); return success ? result('project', useProjectStore.getState().project) : { success: false, error: 'Project not found.' } } }
  ,{ name: 'get_active_project', description: 'Read the active MOOD project.', zod: empty, schema: emptySchema, readOnly: true, execute: () => result('project', useProjectStore.getState().project) }
]

let registrationStarted = false
export const registerMoodTools = async () => {
  const context = (document as WebMcpDocument).modelContext
  if (registrationStarted) return
  registrationStarted = true
  webMcpLifecycle.begin(tools.length, { context: Boolean(context), registerTool: typeof context?.registerTool === 'function' })
  if (typeof context?.registerTool !== 'function') return
  for (const tool of tools) {
    try { await context.registerTool({ name: tool.name, description: tool.description, inputSchema: tool.schema, annotations: tool.readOnly ? { readOnlyHint: true } : undefined, execute: async (input) => tool.execute(tool.zod.parse(input)) }); webMcpLifecycle.registered(tool.name) } catch (error) { webMcpLifecycle.failed(tool.name, error); console.warn(`MOOD could not register ${tool.name}.`, error) }
  }
  let browserTools: unknown[] = []
  if (typeof context.getTools === 'function') {
    try { const found = await context.getTools(); browserTools = Array.isArray(found) ? found : [found]; if (location.hostname === 'localhost' || location.hostname === '127.0.0.1') console.info('MOOD WebMCP diagnostics', found) } catch (error) { webMcpLifecycle.failed('getTools', error) }
  }
  webMcpLifecycle.finish(browserTools)
}
